// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KaneHuxleyAPI
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Station operations.
    /// </summary>
    public partial interface IStation
    {
        /// <param name='board'>
        /// </param>
        /// <param name='crs'>
        /// </param>
        /// <param name='numrows'>
        /// </param>
        /// <param name='board1'>
        /// </param>
        /// <param name='crs1'>
        /// </param>
        /// <param name='filtertype'>
        /// </param>
        /// <param name='filtercrs'>
        /// </param>
        /// <param name='numrows1'>
        /// </param>
        /// <param name='std'>
        /// </param>
        /// <param name='expand'>
        /// </param>
        /// <param name='accesstoken'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetByboardcrsnumrowsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenWithHttpMessagesAsync(string board, string crs, string numrows, int? board1 = default(int?), string crs1 = default(string), int? filtertype = default(int?), string filtercrs = default(string), int? numrows1 = default(int?), string std = default(string), bool? expand = default(bool?), string accesstoken = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='board'>
        /// </param>
        /// <param name='crs'>
        /// </param>
        /// <param name='board1'>
        /// </param>
        /// <param name='crs1'>
        /// </param>
        /// <param name='filtertype'>
        /// </param>
        /// <param name='filtercrs'>
        /// </param>
        /// <param name='numrows'>
        /// </param>
        /// <param name='std'>
        /// </param>
        /// <param name='expand'>
        /// </param>
        /// <param name='accesstoken'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> GetByboardcrsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenWithHttpMessagesAsync(string board, string crs, int? board1 = default(int?), string crs1 = default(string), int? filtertype = default(int?), string filtercrs = default(string), int? numrows = default(int?), string std = default(string), bool? expand = default(bool?), string accesstoken = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
