// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KaneHuxleyAPI
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Station.
    /// </summary>
    public static partial class StationExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='board'>
            /// </param>
            /// <param name='crs'>
            /// </param>
            /// <param name='numrows'>
            /// </param>
            /// <param name='board1'>
            /// </param>
            /// <param name='crs1'>
            /// </param>
            /// <param name='filtertype'>
            /// </param>
            /// <param name='filtercrs'>
            /// </param>
            /// <param name='numrows1'>
            /// </param>
            /// <param name='std'>
            /// </param>
            /// <param name='expand'>
            /// </param>
            /// <param name='accesstoken'>
            /// </param>
            public static object GetByboardcrsnumrowsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstoken(this IStation operations, string board, string crs, string numrows, int? board1 = default(int?), string crs1 = default(string), int? filtertype = default(int?), string filtercrs = default(string), int? numrows1 = default(int?), string std = default(string), bool? expand = default(bool?), string accesstoken = default(string))
            {
                return Task.Factory.StartNew(s => ((IStation)s).GetByboardcrsnumrowsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenAsync(board, crs, numrows, board1, crs1, filtertype, filtercrs, numrows1, std, expand, accesstoken), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='board'>
            /// </param>
            /// <param name='crs'>
            /// </param>
            /// <param name='numrows'>
            /// </param>
            /// <param name='board1'>
            /// </param>
            /// <param name='crs1'>
            /// </param>
            /// <param name='filtertype'>
            /// </param>
            /// <param name='filtercrs'>
            /// </param>
            /// <param name='numrows1'>
            /// </param>
            /// <param name='std'>
            /// </param>
            /// <param name='expand'>
            /// </param>
            /// <param name='accesstoken'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetByboardcrsnumrowsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenAsync(this IStation operations, string board, string crs, string numrows, int? board1 = default(int?), string crs1 = default(string), int? filtertype = default(int?), string filtercrs = default(string), int? numrows1 = default(int?), string std = default(string), bool? expand = default(bool?), string accesstoken = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByboardcrsnumrowsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenWithHttpMessagesAsync(board, crs, numrows, board1, crs1, filtertype, filtercrs, numrows1, std, expand, accesstoken, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='board'>
            /// </param>
            /// <param name='crs'>
            /// </param>
            /// <param name='board1'>
            /// </param>
            /// <param name='crs1'>
            /// </param>
            /// <param name='filtertype'>
            /// </param>
            /// <param name='filtercrs'>
            /// </param>
            /// <param name='numrows'>
            /// </param>
            /// <param name='std'>
            /// </param>
            /// <param name='expand'>
            /// </param>
            /// <param name='accesstoken'>
            /// </param>
            public static object GetByboardcrsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstoken(this IStation operations, string board, string crs, int? board1 = default(int?), string crs1 = default(string), int? filtertype = default(int?), string filtercrs = default(string), int? numrows = default(int?), string std = default(string), bool? expand = default(bool?), string accesstoken = default(string))
            {
                return Task.Factory.StartNew(s => ((IStation)s).GetByboardcrsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenAsync(board, crs, board1, crs1, filtertype, filtercrs, numrows, std, expand, accesstoken), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='board'>
            /// </param>
            /// <param name='crs'>
            /// </param>
            /// <param name='board1'>
            /// </param>
            /// <param name='crs1'>
            /// </param>
            /// <param name='filtertype'>
            /// </param>
            /// <param name='filtercrs'>
            /// </param>
            /// <param name='numrows'>
            /// </param>
            /// <param name='std'>
            /// </param>
            /// <param name='expand'>
            /// </param>
            /// <param name='accesstoken'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetByboardcrsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenAsync(this IStation operations, string board, string crs, int? board1 = default(int?), string crs1 = default(string), int? filtertype = default(int?), string filtercrs = default(string), int? numrows = default(int?), string std = default(string), bool? expand = default(bool?), string accesstoken = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByboardcrsboardcrsfiltertypefiltercrsnumrowsstdexpandaccesstokenWithHttpMessagesAsync(board, crs, board1, crs1, filtertype, filtercrs, numrows, std, expand, accesstoken, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
