// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KaneHuxleyAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ServiceRequest
    {
        /// <summary>
        /// Initializes a new instance of the ServiceRequest class.
        /// </summary>
        public ServiceRequest() { }

        /// <summary>
        /// Initializes a new instance of the ServiceRequest class.
        /// </summary>
        public ServiceRequest(string serviceId = default(string), string accessToken = default(string))
        {
            ServiceId = serviceId;
            AccessToken = accessToken;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceId")]
        public string ServiceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accessToken")]
        public string AccessToken { get; set; }

    }
}
