// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KaneHuxleyAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class StationBoardRequest
    {
        /// <summary>
        /// Initializes a new instance of the StationBoardRequest class.
        /// </summary>
        public StationBoardRequest() { }

        /// <summary>
        /// Initializes a new instance of the StationBoardRequest class.
        /// </summary>
        public StationBoardRequest(int? board = default(int?), string crs = default(string), int? filterType = default(int?), string filterCrs = default(string), int? numRows = default(int?), string std = default(string), bool? expand = default(bool?), string accessToken = default(string))
        {
            Board = board;
            Crs = crs;
            FilterType = filterType;
            FilterCrs = filterCrs;
            NumRows = numRows;
            Std = std;
            Expand = expand;
            AccessToken = accessToken;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "board")]
        public int? Board { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crs")]
        public string Crs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "filterType")]
        public int? FilterType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "filterCrs")]
        public string FilterCrs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numRows")]
        public int? NumRows { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "std")]
        public string Std { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expand")]
        public bool? Expand { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accessToken")]
        public string AccessToken { get; set; }

    }
}
